name: polarization
channels:
        - conda-forge
        - defaults
dependencies:
- libtiff
- matplotlib=2.1.0
- pillow=4.2.1
- imageio=2.2.0
- pandas=0.22.0
- scikit-image=0.13.0
- statsmodels=0.8.0
- numpy=1.13.3
- scikit-learn=0.19.1
- scipy=0.19.1
- seaborn=0.8.1
